### ISSUE TITLE
Change schema structure to accommodate DSN per database.

### ISSUE THREAD

**Issue by naldz** [naldz/FixturamaBundle#3]
```
schema:
  databases:
    db1:
      dsn: dsn1
      tables:
         tb1:
           field1: field_def
           field2: field_def

```
